(()=>{
'use strict';
const $=s=>document.querySelector(s),root=$('#root'),back=$('#back');
const HISTORY=10;
const legacy=localStorage.getItem('bh-balls-v3')||localStorage.getItem('bh-balls-v2')||localStorage.getItem('bh-balls')||'[]';
const state={page:'home',stack:[],balls:safeJSON(legacy,[]),photos:[],target:null,stream:null,timer:null,frames:0,tracks:[],heat:Array(64).fill(0),motion:0,lastGray:null,bestEver:0,parallaxSide:1,aiEngine:null,aiMode:'idle',aiText:'AI not loaded',aiBusy:false,lastAIFrame:0,samBusy:false,lastSamFrame:0};
const colours=[['Green','#85e62f'],['Yellow','#f1dc25'],['Orange','#ff8b22'],['Pink','#ef55af'],['Red','#e64b4b'],['Blue','#3d8ee8'],['White','#eeeeea'],['Purple','#925de6']];
function safeJSON(s,d){try{return JSON.parse(s)}catch{return d}}
function toast(t){const e=$('#toast');if(!e)return;e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1900)}
function save(){localStorage.setItem('bh-balls-v3',JSON.stringify(state.balls))}
function stopCam(){clearInterval(state.timer);state.timer=null;if(state.stream)state.stream.getTracks().forEach(t=>t.stop());state.stream=null}
function go(page,push=true){stopCam();if(push)state.stack.push(state.page);state.page=page;render()}
back.onclick=()=>go(state.stack.pop()||'home',false);
document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));
function nav(){document.querySelectorAll('.nav').forEach(n=>n.classList.toggle('active',n.dataset.go===state.page));back.classList.toggle('hidden',['home','balls','about'].includes(state.page))}
function render(){nav();({home,balls,add,pick,quick,scan,found,about}[state.page]||home)()}
function home(){root.innerHTML=`<section class="hero"><div class="eyebrow">BALLHUNTER VISION V3</div><h1>Find your lost ball <span>smarter.</span></h1><p>V3 combines the fast BallPrint detector with real on-device neural vision. Candidate regions are re-identified against your exact saved ball, then strong matches can be refined with an AI object mask.</p><div class="orb"><div class="ball"></div></div></section><section class="stack"><button class="action primary" id="saved"><div class="ico">◉</div><div><strong>Find my saved ball</strong><small>BallPrint + neural re-identification</small></div><b>→</b></button><button class="action" id="quick"><div class="ico">◐</div><div><strong>Quick colour search</strong><small>Fast mode without neural reference</small></div><b>→</b></button><button class="action" id="add"><div class="ico">＋</div><div><strong>Add a ball before playing</strong><small>Use 1–6 reference photos</small></div><b>→</b></button></section><p class="warning">V3 downloads its neural model only when you search for a saved ball. The first AI search needs internet; after browser caching, later loads can be much faster. Camera frames stay on your device.</p>`;$('#saved').onclick=()=>state.balls.length?go('pick'):go('add');$('#quick').onclick=()=>go('quick');$('#add').onclick=()=>go('add')}
function balls(){root.innerHTML=`<div class="sectionHead"><div><div class="eyebrow">BALL LIBRARY</div><h2>My balls</h2></div><button class="plus" id="plus">+</button></div><div class="balls" id="list"></div>`;$('#plus').onclick=()=>go('add');const l=$('#list');if(!state.balls.length){l.innerHTML=`<div class="panel"><b>No BallPrints yet.</b><p class="copy">Add your exact ball before the game.</p><button class="btn" id="emptyAdd">Add my first ball</button></div>`;$('#emptyAdd').onclick=()=>go('add');return}state.balls.forEach((b,i)=>{const r=document.createElement('div');r.className='card ballRow';r.innerHTML=`<img class="thumb" src="${b.photo}"><div class="grow"><strong>${esc(b.name)}</strong><small>BallPrint V${b.version||1} · ${(b.photos?.length||1)} view${(b.photos?.length||1)>1?'s':''}</small></div><button class="back" title="Delete">×</button>`;r.querySelector('button').onclick=()=>{state.balls.splice(i,1);save();balls()};l.appendChild(r)})}
function add(){state.photos=[];state.pending=null;root.innerHTML=`<div class="sectionHead"><div><div class="eyebrow">BALLPRINT V3</div><h2>Add your ball</h2></div></div><div class="panel"><label class="label">Ball name</label><input id="name" class="input" placeholder="Green tennis ball"><div id="preview" class="preview"><span class="copy">Center the ball and fill most of the frame</span></div><label class="upload">📷 Take / choose 1–6 ball photos<input id="file" type="file" accept="image/*" capture="environment" multiple></label><div class="mini" style="margin-top:9px">Best: front, left, right and top. Keep the ball large in every photo and avoid busy backgrounds.</div></div><div id="fp" class="panel hidden"></div><button id="create" class="btn" style="width:100%" disabled>Create BallPrint V3</button>`;$('#file').onchange=async e=>{const fs=[...e.target.files].slice(0,6);if(!fs.length)return;state.photos=[];for(const f of fs)state.photos.push(await resize(f,320));$('#preview').innerHTML=`<img src="${state.photos[0]}">`;const fp=await multiFingerprint(state.photos);state.pending=fp;$('#fp').classList.remove('hidden');$('#fp').innerHTML=`<div class="finger"><div class="swatch" style="background:${fp.hex}"></div><div><b>BallPrint V3 reference ready</b><div class="mini">${state.photos.length} view${state.photos.length>1?'s':''} · colour ${fp.hex} · texture ${Math.round(fp.edge*100)}%</div></div></div><div class="photoDots">${state.photos.map(p=>`<img class="photoDot" src="${p}">`).join('')}</div>`;$('#create').disabled=false};$('#create').onclick=()=>{const name=$('#name').value.trim()||'My ball';state.balls.unshift({id:Date.now(),name,photo:state.photos[0],photos:state.photos,version:3,...state.pending});save();toast('BallPrint V3 saved');go('balls')}}
function pick(){root.innerHTML=`<div class="sectionHead"><div><div class="eyebrow">REFERENCE SEARCH</div><h2>Select your ball</h2></div></div><p class="copy">V3 will build neural image embeddings from the saved reference views and compare live candidate crops against them.</p><div id="pickList" class="balls"></div>`;state.balls.forEach(b=>{const r=document.createElement('button');r.className='action';r.innerHTML=`<img class="thumb" src="${b.photo}"><div><strong>${esc(b.name)}</strong><small>BallPrint V${b.version||1} · ${(b.photos?.length||1)} AI reference view${(b.photos?.length||1)>1?'s':''}</small></div><b>→</b>`;r.onclick=()=>{state.target=normalizeTarget(b);go('scan')};$('#pickList').appendChild(r)})}
function quick(){root.innerHTML=`<div class="sectionHead"><div><div class="eyebrow">QUICK SEARCH</div><h2>Ball colour</h2></div></div><p class="copy">Choose the closest colour. This mode uses V2 shape, contrast and persistence but skips neural re-identification because there is no exact reference image.</p><div class="colourGrid" id="cg"></div><div class="panel customRow"><input id="custom" type="color" value="#85e62f"><div><b id="hex">#85E62F</b><div class="mini">Custom target colour</div></div></div><button class="btn" id="start" style="width:100%">Start camera search</button>`;let active='#85e62f';colours.forEach(([n,c])=>{const b=document.createElement('button');b.className='colour'+(c===active?' active':'');b.style.background=c;b.title=n;b.onclick=()=>{active=c;$('#custom').value=c;$('#hex').textContent=c.toUpperCase();document.querySelectorAll('.colour').forEach(x=>x.classList.remove('active'));b.classList.add('active')};$('#cg').appendChild(b)});$('#custom').oninput=e=>{active=e.target.value;$('#hex').textContent=active.toUpperCase();document.querySelectorAll('.colour').forEach(x=>x.classList.remove('active'))};$('#start').onclick=()=>{const [h,s,v]=rgb2hsv(...hex2rgb(active));state.target={name:'Quick colour ball',h,s,v,hex:active,hist:histForHue(h),edge:.18,sStd:.18,vStd:.18,quick:true,version:3,photos:[]};go('scan')}}
function scan(){resetSearch();root.innerHTML=`<div class="scannerTop"><div><div class="eyebrow">LIVE SEARCH · V3</div><b>${esc(state.target.name)}</b></div><span class="pill" id="status">READY</span></div><div class="cameraWrap"><video id="video" autoplay playsinline muted></video><canvas id="overlay"></canvas><div id="ask" class="camAsk"><div><div class="ico">◉</div><h3>Camera access needed</h3><p class="copy">Use the rear camera. Sweep slowly, then move sideways around suspicious areas.</p><button class="btn" id="enable">Enable camera</button></div></div></div><div class="metrics"><div class="metric"><small>Fused match</small><b id="best">0%</b></div><div class="metric"><small>Neural match</small><b id="neural">—</b></div><div class="metric"><small>Persistence</small><b id="persist">0%</b></div></div><div class="bar"><i id="bar"></i></div><div class="signalRow"><span class="signal" id="sigColour">Colour</span><span class="signal" id="sigShape">Shape</span><span class="signal" id="sigTime">Multi-frame</span><span class="signal" id="sigAI">Neural re-ID</span><span class="signal" id="sigMask">AI mask</span></div><div class="aiCard" id="aiCard"><div class="aiDot" id="aiDot"></div><div><strong id="aiTitle">${state.target.quick?'Quick mode':'Neural vision waiting'}</strong><small id="aiText">${state.target.quick?'No reference image — neural re-ID is off.':'AI loads after camera starts.'}</small></div></div><div class="guide"><small>Live guidance</small><b id="guide">Move slowly and scan the ground</b></div><div id="candidate" class="candidateCard"><strong id="candTitle">Possible ball</strong><div class="candidateMeta"><span id="candShape"></span><span id="candPersist"></span><span id="candAI"></span></div><button id="foundBtn" class="btn" style="width:100%;margin-top:10px">I found the ball</button></div><div class="searchMap" id="map">${Array.from({length:64},()=>'<i class="mapCell"></i>').join('')}</div><div class="warning">Neural re-ID compares candidate image embeddings against your saved ball. SlimSAM mask refinement is triggered only for a strong persistent candidate. A fully hidden opaque ball still cannot be visually confirmed by an RGB camera.</div>`;$('#enable').onclick=startCam;$('#foundBtn').onclick=()=>go('found')}
function resetSearch(){state.frames=0;state.tracks=[];state.heat=Array(64).fill(0);state.motion=0;state.lastGray=null;state.bestEver=0;state.parallaxSide=1;state.aiMode=state.target?.quick?'off':'idle';state.aiText=state.target?.quick?'Quick mode':'AI not loaded';state.aiBusy=false;state.lastAIFrame=0;state.samBusy=false;state.lastSamFrame=0}
async function startCam(){try{if(!navigator.mediaDevices?.getUserMedia)throw new Error('Camera API unavailable');state.stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1280},height:{ideal:720}},audio:false});const v=$('#video');v.srcObject=state.stream;await v.play();$('#ask').classList.add('hidden');$('#status').textContent='SCANNING';state.timer=setInterval(analyse,180);if(!state.target.quick)startNeuralVision()}catch(e){console.error(e);toast('Camera permission failed');$('#guide').textContent='Allow camera permission in browser settings, then reload this page'}}
async function startNeuralVision(){if(state.aiMode==='loading'||state.aiMode==='ready')return;state.aiMode='loading';setAIStatus('loading','Loading ONNX neural vision','Downloading/caching the vision model. Camera scanning continues.');try{const mod=await import('./ai-engine.js');state.aiEngine=mod.BallHunterAI;await state.aiEngine.init(onAIProgress);const refs=[];for(const src of state.target.photos.slice(0,6))refs.push(await imageToCanvas(src,224));await state.aiEngine.setReferenceCanvases(refs,onAIProgress);state.aiMode='ready';const st=state.aiEngine.status;setAIStatus('ready','Neural re-ID ready',`${st.device.toUpperCase()} · ${st.references} saved reference view${st.references===1?'':'s'}`)}catch(e){console.error('AI init failed',e);state.aiMode='error';setAIStatus('error','Neural model unavailable','V2 detector remains active. Check connection/browser support and retry by reopening search.')}}
function onAIProgress(e){let text=e.text||'';const p=e.detail?.progress;if(!text&&Number.isFinite(p))text=`Model ${Math.round(p)}%`;if(!text&&e.detail?.file)text=`Loading ${String(e.detail.file).split('/').pop()}`;if(text){state.aiText=text;setAIStatus('loading','Preparing neural vision',text)}}
function setAIStatus(mode,title,text){const card=$('#aiCard');if(!card)return;card.dataset.mode=mode;$('#aiTitle').textContent=title;$('#aiText').textContent=text||'';$('#aiDot').className='aiDot '+mode}
function analyse(){const v=$('#video'),o=$('#overlay');if(!v?.videoWidth||!o)return;const cssW=Math.max(1,v.clientWidth),cssH=Math.max(1,v.clientHeight),ratio=Math.min(2,window.devicePixelRatio||1);o.width=Math.round(cssW*ratio);o.height=Math.round(cssH*ratio);const W=224,H=Math.max(168,Math.round(W*cssH/cssW)),c=document.createElement('canvas');c.width=W;c.height=H;const x=c.getContext('2d',{willReadFrequently:true});drawVideoCover(x,v,W,H);const img=x.getImageData(0,0,W,H),d=img.data,sim=new Float32Array(W*H),mask=new Uint8Array(W*H),gray=new Uint8Array(W*H);let meanMotion=0;for(let i=0,p=0;i<d.length;i+=4,p++){const r=d[i],g=d[i+1],b=d[i+2];gray[p]=(r*3+g*6+b)/10;const [h,s,val]=rgb2hsv(r,g,b),q=colourSimilarity(h,s,val,state.target);sim[p]=q;if(q>.48)mask[p]=1;if(state.lastGray)meanMotion+=Math.abs(gray[p]-state.lastGray[p])}state.motion=state.lastGray?state.motion*.7+(meanMotion/(W*H*255))*.3:0;state.lastGray=gray;const candidates=findComponents(mask,sim,d,W,H);updateTracks(candidates);state.frames++;if(state.aiMode==='ready'&&!state.aiBusy&&state.frames-state.lastAIFrame>=8)scheduleAIRerank(c,W,H);const best=bestTrack();if(best){state.bestEver=Math.max(state.bestEver,best.score);updateHeat(best.x/W,best.y/H,best.score)}drawOverlay(o,best,candidates,W,H);updateUI(best)}
async function scheduleAIRerank(frame,W,H){state.aiBusy=true;state.lastAIFrame=state.frames;try{const todo=state.tracks.filter(t=>t.misses<2&&t.baseScore>.34).sort((a,b)=>b.baseScore-a.baseScore).slice(0,3).map(t=>({id:t.id,crop:cropCandidate(frame,t,W,H)}));for(const item of todo){const out=await state.aiEngine.similarity(item.crop);const t=state.tracks.find(x=>x.id===item.id);if(!t)continue;t.aiRaw=out.raw;t.aiScore=t.aiScore==null?out.score:t.aiScore*.58+out.score*.42;t.score=fuseScore(t);if(t.aiScore>.58&&t.persistence>.42&&!t.samAttempted&&!state.samBusy&&state.frames-state.lastSamFrame>24){t.samAttempted=true;segmentTrack(item.crop,t.id)}}}catch(e){console.warn('Neural rerank failed',e)}finally{state.aiBusy=false}}
async function segmentTrack(crop,id){state.samBusy=true;state.lastSamFrame=state.frames;setAIStatus('loading','Refining candidate mask','SlimSAM is checking the shape of the strongest neural candidate.');try{const out=await state.aiEngine.segmentCandidate(crop,onAIProgress);const t=state.tracks.find(x=>x.id===id);if(t){t.maskScore=out.score;t.maskMeta=out;t.score=fuseScore(t)}const st=state.aiEngine.status;setAIStatus('ready','Neural re-ID + mask ready',`${st.device.toUpperCase()} · candidate boundary refined`)}catch(e){console.warn('Mask refinement failed',e);setAIStatus('ready','Neural re-ID ready','Mask refinement skipped; neural image matching remains active.')}finally{state.samBusy=false}}
function fuseScore(t){let s=t.baseScore||0;if(t.aiScore!=null)s=.70*s+.30*t.aiScore;if(t.maskScore!=null)s=.84*s+.16*t.maskScore;return clamp(s)}
function bestTrack(){return state.tracks.filter(t=>t.misses<5).sort((a,b)=>b.score-a.score)[0]||null}
function findComponents(mask,sim,data,W,H){const seen=new Uint8Array(W*H),out=[],q=new Int32Array(W*H);for(let p=0;p<mask.length;p++){if(!mask[p]||seen[p])continue;let head=0,tail=0;q[tail++]=p;seen[p]=1;let area=0,sumX=0,sumY=0,sumQ=0,maxQ=0,minX=W,maxX=0,minY=H,maxY=0,per=0;while(head<tail){const cur=q[head++],y=Math.floor(cur/W),xx=cur-y*W;area++;sumX+=xx;sumY+=y;sumQ+=sim[cur];maxQ=Math.max(maxQ,sim[cur]);minX=Math.min(minX,xx);maxX=Math.max(maxX,xx);minY=Math.min(minY,y);maxY=Math.max(maxY,y);let border=0;const ns=[cur-1,cur+1,cur-W,cur+W];for(let k=0;k<4;k++){const n=ns[k],nx=k===0?xx-1:k===1?xx+1:xx,ny=k===2?y-1:k===3?y+1:y;if(nx<0||nx>=W||ny<0||ny>=H||!mask[n]){border++;continue}if(!seen[n]){seen[n]=1;q[tail++]=n}}per+=border}if(area<5||area>W*H*.16)continue;const bw=maxX-minX+1,bh=maxY-minY+1,aspect=Math.min(bw,bh)/Math.max(bw,bh),fill=area/(bw*bh),circular=Math.min(1,(4*Math.PI*area)/(per*per||1)),cx=sumX/area,cy=sumY/area,meanQ=sumQ/area,contrast=localContrast(data,W,H,cx,cy,bw,bh,state.target),compact=Math.min(1,.45*aspect+.35*Math.min(1,fill/.72)+.2*Math.min(1,circular/.55)),partial=Math.min(1,.65*compact+.35*Math.min(1,maxQ)),shape=state.target.quick?partial:Math.min(1,partial*.85+(1-Math.abs((state.target.edge||.18)-estimateEdge(fill,circular)))*.15);let score=.52*meanQ+.18*maxQ+.18*shape+.12*contrast;if(area<12)score*=.85;out.push({x:cx,y:cy,w:bw,h:bh,area,meanQ,maxQ,shape,contrast,score:clamp(score),circular,fill})}return out.sort((a,b)=>b.score-a.score).slice(0,12)}
function localContrast(data,W,H,cx,cy,bw,bh,target){const r=Math.max(8,Math.min(28,Math.max(bw,bh)*1.6)),r0=Math.max(3,Math.max(bw,bh)*.55);let inner=0,outer=0,ni=0,no=0;for(let y=Math.max(0,Math.floor(cy-r));y<=Math.min(H-1,Math.ceil(cy+r));y+=2)for(let x=Math.max(0,Math.floor(cx-r));x<=Math.min(W-1,Math.ceil(cx+r));x+=2){const dist=Math.hypot(x-cx,y-cy),i=(y*W+x)*4,[h,s,v]=rgb2hsv(data[i],data[i+1],data[i+2]),q=colourSimilarity(h,s,v,target);if(dist<r0){inner+=q;ni++}else if(dist<r){outer+=q;no++}}if(!ni||!no)return .5;return clamp(.5+(inner/ni-outer/no)*1.4)}
function updateTracks(cands){for(const t of state.tracks){t.misses++;t.age++}for(const c of cands){let best=null,bd=Infinity;for(const t of state.tracks){const dist=Math.hypot(c.x-t.x,c.y-t.y),gate=Math.max(16,Math.max(c.w,c.h,t.w,t.h)*1.8);if(dist<gate&&dist<bd){bd=dist;best=t}}if(best){best.x=best.x*.55+c.x*.45;best.y=best.y*.55+c.y*.45;best.w=best.w*.65+c.w*.35;best.h=best.h*.65+c.h*.35;best.raw=c;best.hits++;best.misses=0;best.persistence=Math.min(1,best.hits/HISTORY);best.baseScore=clamp(.55*c.score+.25*(best.baseScore||best.score)+.2*best.persistence);best.score=fuseScore(best)}else state.tracks.push({id:crypto.randomUUID?.()||Math.random().toString(36),x:c.x,y:c.y,w:c.w,h:c.h,raw:c,hits:1,misses:0,age:1,persistence:.1,baseScore:c.score*.75,score:c.score*.75,aiScore:null,maskScore:null,samAttempted:false})}state.tracks=state.tracks.filter(t=>t.misses<10&&t.age<260);for(const t of state.tracks)if(t.misses){t.baseScore*=.92;t.score=fuseScore(t);t.persistence*=.96}}
function cropCandidate(src,t,W,H){const out=document.createElement('canvas');out.width=out.height=224;const g=out.getContext('2d');g.fillStyle='#111';g.fillRect(0,0,224,224);const side=Math.max(26,Math.min(Math.max(W,H),Math.max(t.w,t.h)*2.8)),sx=Math.max(0,Math.min(W-side,t.x-side/2)),sy=Math.max(0,Math.min(H-side,t.y-side/2)),sw=Math.min(side,W-sx),sh=Math.min(side,H-sy);g.drawImage(src,sx,sy,sw,sh,0,0,224,224);return out}
function updateHeat(nx,ny,score){const gx=Math.max(0,Math.min(7,Math.floor(nx*8))),gy=Math.max(0,Math.min(7,Math.floor(ny*8))),idx=gy*8+gx;for(let i=0;i<64;i++)state.heat[i]*=.985;state.heat[idx]=Math.max(state.heat[idx],score);document.querySelectorAll('.mapCell').forEach((e,i)=>{const v=state.heat[i];e.className='mapCell'+(v>.72?' high':v>.48?' mid':v>.25?' low':'')})}
function updateUI(best){if(!best){$('#best').textContent='0%';$('#neural').textContent='—';$('#persist').textContent='0%';$('#status').textContent='SCANNING';$('#guide').textContent=state.motion<.008?'Move the phone slowly to a new area':'Keep sweeping slowly across the ground';$('#candidate').classList.remove('show');setSignals(null);return}const pct=Math.round(best.score*100),persist=Math.round(best.persistence*100),r=best.raw||{};$('#best').textContent=pct+'%';$('#persist').textContent=persist+'%';$('#neural').textContent=best.aiScore==null?(state.aiMode==='loading'?'…':'—'):Math.round(best.aiScore*100)+'%';$('#bar').style.width=Math.max(4,pct)+'%';setSignals({colour:r.meanQ>.58,shape:r.shape>.48,time:best.persistence>.45,ai:(best.aiScore||0)>.55,mask:(best.maskScore||0)>.55});$('#candidate').classList.toggle('show',pct>=46);$('#candTitle').textContent=pct>=80?'Strong ball candidate':pct>=60?'AI-supported candidate':'Possible ball candidate';$('#candShape').textContent=`shape ${Math.round((r.shape||0)*100)}%`;$('#candPersist').textContent=`seen ${best.hits} frames`;$('#candAI').textContent=best.aiScore==null?'AI pending':`neural ${Math.round(best.aiScore*100)}%`;let guide;if(pct>=84&&best.persistence>.62&&(best.aiScore==null||best.aiScore>.55))guide='Strong fused match — inspect the highlighted spot closely';else if(pct>=64){const side=state.parallaxSide>0?'right':'left';guide=`Candidate detected — move about 30 cm ${side} while keeping it in view`;if(state.frames%24===0)state.parallaxSide*=-1}else if(pct>=45)guide='Weak candidate — lower the camera and scan it from another angle';else guide=state.motion<.006?'Move slowly to reveal new ground':'Continue a slow sweep';$('#guide').textContent=guide;$('#guide').classList.toggle('found',pct>=78);$('#status').textContent=pct>=78?'HIGH MATCH':pct>=48?'POSSIBLE':'SCANNING'}
function setSignals(s){[['#sigColour','colour'],['#sigShape','shape'],['#sigTime','time'],['#sigAI','ai'],['#sigMask','mask']].forEach(([sel,k])=>$(sel)?.classList.toggle('on',!!s?.[k]))}
function drawOverlay(o,best,cands,W,H){const g=o.getContext('2d');g.clearRect(0,0,o.width,o.height);const sx=o.width/W,sy=o.height/H;for(const c of cands.slice(0,5)){if(c.score<.42)continue;g.strokeStyle='rgba(255,212,91,.28)';g.lineWidth=1.5*(window.devicePixelRatio||1);g.strokeRect((c.x-c.w/2)*sx,(c.y-c.h/2)*sy,c.w*sx,c.h*sy)}if(!best)return;const pct=best.score;g.strokeStyle=pct>.78?'#83f23c':pct>.48?'#ffd45b':'#ffffff66';g.lineWidth=3*(window.devicePixelRatio||1);g.setLineDash([10,6]);g.strokeRect((best.x-best.w/2)*sx-8,(best.y-best.h/2)*sy-8,best.w*sx+16,best.h*sy+16);g.setLineDash([]);if(pct>.42){g.fillStyle=pct>.78?'#83f23c':'#ffd45b';g.font=`700 ${13*(window.devicePixelRatio||1)}px system-ui`;g.fillText(`V3 fused ${Math.round(pct*100)}%`,Math.max(8,(best.x-best.w/2)*sx),Math.max(24,(best.y-best.h/2)*sy-12))}}
function found(){root.innerHTML=`<section class="hero" style="text-align:center;padding-top:45px"><div class="eyebrow">RECOVERY COMPLETE</div><div class="orb" style="margin-top:18px"><div class="ball"></div></div><h1 style="font-size:34px">Ball <span>found.</span></h1><p>Your BallPrint remains saved on this device. V3 does not upload the camera session.</p><button class="btn" id="again" style="width:100%;margin-top:10px">Back to home</button></section>`;$('#again').onclick=()=>go('home')}
function about(){root.innerHTML=`<div class="sectionHead"><div><div class="eyebrow">HOW IT WORKS</div><h2>BallHunter V3</h2></div></div><div class="stack"><div class="panel"><b>1 · Multi-view BallPrint</b><p class="copy">One to six reference images capture the ball's colour distribution and texture. V3 also keeps the views for neural reference embeddings.</p></div><div class="panel"><b>2 · Fast candidate proposals</b><p class="copy">The phone first finds compact colour/shape fragments cheaply, so the neural network does not waste time analysing every pixel region.</p></div><div class="panel"><b>3 · Neural re-identification</b><p class="copy">A quantized CLIP vision encoder runs through ONNX in the browser and compares learned image embeddings from candidate crops with your saved ball views.</p></div><div class="panel"><b>4 · SlimSAM mask refinement</b><p class="copy">When a candidate is strong and persistent, a compact Segment Anything model can refine the object mask and contribute a shape score.</p></div><div class="panel"><b>5 · Temporal + parallax reasoning</b><p class="copy">The fused candidate persists across frames and the app asks you to change viewpoint, helping reveal edges hidden by grass or leaves.</p></div><div class="panel"><b>6 · Physical limit</b><p class="copy">No RGB model can recover pixels blocked by a completely opaque object. A future Play Mode must add trajectory/disappearance evidence for fully hidden cases.</p></div></div>`}
async function imageToCanvas(src,size=224){return new Promise((res,rej)=>{const im=new Image;im.onload=()=>{const c=document.createElement('canvas');c.width=c.height=size;const g=c.getContext('2d'),s=Math.min(im.width,im.height),sx=(im.width-s)/2,sy=(im.height-s)/2;g.drawImage(im,sx,sy,s,s,0,0,size,size);res(c)};im.onerror=rej;im.src=src})}
async function resize(file,max){return new Promise((res,rej)=>{const r=new FileReader;r.onload=()=>{const im=new Image;im.onload=()=>{const sc=Math.min(1,max/Math.max(im.width,im.height)),c=document.createElement('canvas');c.width=Math.round(im.width*sc);c.height=Math.round(im.height*sc);c.getContext('2d').drawImage(im,0,0,c.width,c.height);res(c.toDataURL('image/jpeg',.75))};im.onerror=rej;im.src=r.result};r.onerror=rej;r.readAsDataURL(file)})}
async function multiFingerprint(srcs){const fps=[];for(const s of srcs)fps.push(await fingerprint(s));const hist=Array(36).fill(0);let hSin=0,hCos=0,s=0,v=0,sStd=0,vStd=0,edge=0;for(const f of fps){for(let i=0;i<36;i++)hist[i]+=f.hist[i]/fps.length;const rad=f.h*Math.PI/180;hSin+=Math.sin(rad);hCos+=Math.cos(rad);s+=f.s;v+=f.v;sStd+=f.sStd;vStd+=f.vStd;edge+=f.edge}const h=(Math.atan2(hSin,hCos)*180/Math.PI+360)%360;return{h,s:s/fps.length,v:v/fps.length,sStd:sStd/fps.length,vStd:vStd/fps.length,edge:edge/fps.length,hist,hex:rgb2hex(hsv2rgb(h,s/fps.length,v/fps.length))}}
async function fingerprint(src){return new Promise(res=>{const im=new Image;im.onload=()=>{const c=document.createElement('canvas');c.width=c.height=180;const x=c.getContext('2d',{willReadFrequently:true});x.drawImage(im,0,0,180,180);const d=x.getImageData(0,0,180,180).data,hist=Array(36).fill(0),samples=[];let ss=0,vs=0,n=0,edges=0,prev=null;for(let y=18;y<162;y+=2)for(let xx=18;xx<162;xx+=2){if(Math.hypot(xx-90,y-90)>69)continue;const i=(y*180+xx)*4,[h,s,v]=rgb2hsv(d[i],d[i+1],d[i+2]);if(v>.1){hist[Math.floor(h/10)%36]+=Math.max(.12,s)*v;ss+=s;vs+=v;samples.push([s,v]);n++}const lum=(d[i]*3+d[i+1]*6+d[i+2])/10;if(prev!==null&&Math.abs(lum-prev)>28)edges++;prev=lum}const sum=hist.reduce((a,b)=>a+b,0)||1;for(let i=0;i<36;i++)hist[i]/=sum;let xh=0,yh=0;hist.forEach((w,i)=>{const a=(i*10+5)*Math.PI/180;xh+=Math.cos(a)*w;yh+=Math.sin(a)*w});const h=(Math.atan2(yh,xh)*180/Math.PI+360)%360,s=ss/Math.max(1,n),v=vs/Math.max(1,n);let sv=0,vv=0;for(const [a,b] of samples){sv+=(a-s)*(a-s);vv+=(b-v)*(b-v)}res({h,s,v,sStd:Math.sqrt(sv/Math.max(1,n)),vStd:Math.sqrt(vv/Math.max(1,n)),edge:clamp(edges/Math.max(1,n)*4),hist,hex:rgb2hex(hsv2rgb(h,s,v))})};im.src=src})}
function normalizeTarget(b){const photos=b.photos?.length?b.photos:[b.photo].filter(Boolean);if((b.version||1)>=2&&b.hist)return{...b,photos,quick:false};return{name:b.name,h:b.h,s:b.s,v:b.v,hex:b.hex,hist:histForHue(b.h),edge:.18,sStd:.2,vStd:.2,quick:false,version:b.version||1,photos}}
function histForHue(h){const a=Array(36).fill(0),i=Math.floor(h/10)%36;a[i]=.6;a[(i+35)%36]=.2;a[(i+1)%36]=.2;return a}
function colourSimilarity(h,s,v,t){const hd=Math.min(Math.abs(h-t.h),360-Math.abs(h-t.h)),hueWeight=Math.max(.08,Math.min(1,(t.s+.15)*(s+.15))),hue=Math.max(0,1-hd/72),sat=Math.max(0,1-Math.abs(s-t.s)/Math.max(.35,(t.sStd||.2)*3)),val=Math.max(0,1-Math.abs(v-t.v)/Math.max(.42,(t.vStd||.2)*3)),bin=Math.floor(h/10)%36,hist=t.hist?.[bin]||0,histScore=Math.min(1,hist*5.5);return clamp((.48*hue*hueWeight+.24*sat+.2*val+.08*histScore)/(.48*hueWeight+.52))}
function estimateEdge(fill,circ){return clamp((1-fill)*.45+(1-circ)*.25+.08)}
function drawVideoCover(ctx,v,W,H){const va=v.videoWidth/v.videoHeight,ta=W/H;let sx=0,sy=0,sw=v.videoWidth,sh=v.videoHeight;if(va>ta){sw=v.videoHeight*ta;sx=(v.videoWidth-sw)/2}else{sh=v.videoWidth/ta;sy=(v.videoHeight-sh)/2}ctx.drawImage(v,sx,sy,sw,sh,0,0,W,H)}
function rgb2hsv(r,g,b){r/=255;g/=255;b/=255;let M=Math.max(r,g,b),m=Math.min(r,g,b),d=M-m,h=0;if(d){if(M===r)h=60*((g-b)/d%6);else if(M===g)h=60*((b-r)/d+2);else h=60*((r-g)/d+4)}if(h<0)h+=360;return[h,M?d/M:0,M]}
function hsv2rgb(h,s,v){let c=v*s,x=c*(1-Math.abs(h/60%2-1)),m=v-c,r=0,g=0,b=0;if(h<60)[r,g,b]=[c,x,0];else if(h<120)[r,g,b]=[x,c,0];else if(h<180)[r,g,b]=[0,c,x];else if(h<240)[r,g,b]=[0,x,c];else if(h<300)[r,g,b]=[x,0,c];else[r,g,b]=[c,0,x];return[r,g,b].map(q=>Math.round((q+m)*255))}
function hex2rgb(h){h=h.replace('#','');return[0,2,4].map(i=>parseInt(h.slice(i,i+2),16))}
function rgb2hex(a){return'#'+a.map(v=>v.toString(16).padStart(2,'0')).join('').toUpperCase()}
function clamp(v){return Math.max(0,Math.min(1,v))}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
render();
})();
